server {
    listen 80;
    server_name web1.trinhquyen.id.vn;

    location / {
        root /usr/share/nginx/html/web1;
        index index.html;
    }

    # Cấu hình gọi ngầm sang API của Node-RED
    location /api/ {
        proxy_pass http://nodered:1880;
    }
}
