server {
    listen 80;
    server_name domain1.com; # Doi thanh domain 1 cua ban

    root /usr/share/nginx/html/site1;
    index index.html;

    location /api/ {
        proxy_pass http://nodered:1880/;
        proxy_set_header Host $host;
    }
}
